# use the Apache Airflow base image
FROM apache/airflow:2.5.1-python3.9

# copy DAGs and requirements
COPY generate_data.py /usr/local/airflow/dags/
COPY requirements.txt /requirements.txt

# install dependencies
RUN pip install --no-cache-dir -r /requirements.txt

# run Airflow
CMD ["python", "/usr/local/airflow/dags/generate_data.py"]
